server:
  port: 10030
  servlet:
    context-path: /admin-server
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: admin-server
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB


# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  global-config:
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      # 驼峰命名
      column-underline: true
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
